name: flutter_clean_architecture
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  # di
  get_it: ^7.6.7
  # equatable
  equatable: ^2.0.5
  # state manager
  flutter_bloc: ^8.1.3
  # hive
  hive: ^2.2.3
  # path
  path_provider: ^2.1.2
  # rest api
  dio: ^5.4.0
  dio_retry_plus: ^2.0.5
  chuck_interceptor: ^2.0.8
  # box
  gap: ^3.0.1
  # router
  go_router: ^13.1.0
  # svg
  flutter_svg: ^2.0.9
  # url launchers
  url_launcher: ^6.2.4
  # sms autofill
  sms_autofill:
    git:
      url: https://github.com/SunnatilloShavkatov/sms_autofill.git
      ref: staging
  # package info
  package_info_plus: ^5.0.1
  # cached image
  cached_network_image: ^3.3.1
  # native splash
  flutter_native_splash: ^2.3.9
  # firebase
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_messaging: ^14.7.10
  firebase_remote_config: ^4.3.8
  # local notification
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  bloc_test: ^9.1.5
  mockito: ^5.4.4

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/locale/
    - assets/images/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
